version: '3.1'
services:
  mssql_2019:
    image: mcr.microsoft.com/mssql/server:2019-latest
    user: '0:0'
    
    restart: always
    hostname: mssql2019
    ports:
      - 1433:1433
    container_name: mssql19
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Admin#532
      MSSQL_PID: Express
      MSSQL_LCID: 3082
      MSSQL_COLLATION: Modern_Spanish_CI_AS      
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./var/opt/mssql:/var/opt/mssql/
    
